spring:
  flyway:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=30;
    user: sa
    password: password
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
